### ISSUE TITLE
Media Page Routing 

### ISSUE THREAD

**Issue by bamboochow** [pcl-labs/browtricks-ui-components#18]
# Show Alert

Hide this button and only show alert on upload action. 

For the purposes of the demo program, when image is uploaded, show all 3 potential alert versions on the page. 

![image](https://user-images.githubusercontent.com/14948326/214921723-352c66a5-aa15-44c0-8da2-aa9e84e302c2.png)

# Your Media

Route this section based on circle color from screenshot below

Red:
When you click on this, the "Edit Media" slide module should slide in for that upload

Blue:
When you click any of these, page should redirect to /customer-edit of selected customer

Green:
When you click this, copy link of media

![image](https://user-images.githubusercontent.com/14948326/214922211-200cc0c6-2da5-46e6-b68e-3e3c58caec69.png)

# Empty Page Routing 

"Connect Socials" Should open /settings
"Add Manually" should open slide in media module to add a new upload

![image](https://user-images.githubusercontent.com/14948326/214922490-71bdc8a8-041e-4f10-8c96-e82011171e86.png)

**Comment by paulchrisluke** [comment]
we are going to further edit this page to make it easier to understand, closing this for now
