### ISSUE TITLE
Create "Create account" page

### ISSUE THREAD

**Issue by giteshk11** [pcl-labs/browtricks-ui-components#2]
Create a "Create account" page which would help our users to sign up for our app.

Things to note:
- Page should be built from reusable components created earlier.
- Page should be responsive for all screen sizes.
- Input fields should have validations.

Figma : [https://www.figma.com/file/kwIHq0NTQUDBryrkZVN1ap/browtricks-cms?node-id=915%3A2750&t=KyXE7VMEsBV6L8TG-0](https://www.figma.com/file/kwIHq0NTQUDBryrkZVN1ap/browtricks-cms?node-id=915%3A2750&t=KyXE7VMEsBV6L8TG-0)

![Image](https://user-images.githubusercontent.com/17675390/205345467-66aa858c-957f-43ae-9ad3-0973c7265125.png)

**Comment by kshekh** [comment]
The page has been built with reusable components. 
Page is fully responsive for all screens and as per design in Figma
The input fields have their validation but work when the form will be built
