### ISSUE TITLE
Create "Login" and "Forgot password" pages

### ISSUE THREAD

**Issue by giteshk11** [pcl-labs/browtricks-ui-components#3]
Create a "Login" page that will help our users to login into our app.
Create a "Forgot password" page which will ours to easily reset their passwords.

Things to note:
The page should be built from reusable components created earlier.
The page should be responsive for all screen sizes.
Input fields should have validations.

Figma : https://www.figma.com/file/kwIHq0NTQUDBryrkZVN1ap/browtricks-cms?node-id=915%3A2849&t=KyXE7VMEsBV6L8TG-0

### Login
![Image](https://user-images.githubusercontent.com/17675390/205346798-4c247c24-180b-4a65-8e44-738287c22f6d.png)

### Forgot password

![Image](https://user-images.githubusercontent.com/17675390/205347055-a0e320ee-0fb7-431c-af4f-1f8fec06d72e.png)

**Comment by kshekh** [comment]
Both pages have been built with reusable components
Both pages are fully responsive as per Figma Design
Input fields have their validations
