### ISSUE TITLE
Create User profile page

### ISSUE THREAD

**Issue by giteshk11** [pcl-labs/browtricks-ui-components#5]
Create a user profile page/settings that let users change their settings in the app.

Figma (User Profile) https://www.figma.com/file/kwIHq0NTQUDBryrkZVN1ap/browtricks-cms?node-id=915%3A4722&t=yxR0yIP5GWnyILT9-0

(User Settings) https://www.figma.com/file/kwIHq0NTQUDBryrkZVN1ap/browtricks-cms?node-id=921%3A7077&t=yxR0yIP5GWnyILT9-0

**Comment by kshekh** [comment]
Thew user profile and user settings pages have been built
